/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_searchscale_lucene_vectorsearch_jni_CuVSIndexJni */

#ifndef _Included_com_searchscale_lucene_vectorsearch_jni_CuVSIndexJni
#define _Included_com_searchscale_lucene_vectorsearch_jni_CuVSIndexJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_searchscale_lucene_vectorsearch_jni_CuVSIndexJni
 * Method:    initIndex
 * Signature: ([I[FII)I
 */
JNIEXPORT jint JNICALL Java_com_searchscale_lucene_vectorsearch_jni_CuVSIndexJni_initIndex
  (JNIEnv *, jobject, jintArray, jfloatArray, jint, jint);

/*
 * Class:     com_searchscale_lucene_vectorsearch_jni_CuVSIndexJni
 * Method:    getTopK
 * Signature: ([FI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_searchscale_lucene_vectorsearch_jni_CuVSIndexJni_getTopK
  (JNIEnv *, jobject, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
